pics: elliptic.plot ellipticsum.plot
	gnuplot elliptic.plot
	gnuplot ellipticsum.plot
	gnuplot ellipticsumeq.plot
	gnuplot ellipticsumeq2.plot
	gnuplot ellipticfp.plot

all ps pdf install clean: 
	$(MAKE) -C ../../ $@
.PHONY : all ps pdf install clean
